### ISSUE TITLE
Werid duplicate symbol error

### ISSUE THREAD

**Issue by form2l1n** [EOSIO/eosio.cdt#545]
I just want to follow the guide in official website, but seems strange things happen
```
#include <eosio/eosio.hpp>
#include <eosio/asset.hpp>
#include <eosio/transaction.hpp>
```
Every time  I put those thing together, there will be error like this
```
/usr/local/Cellar/eosio.cdt/1.6.1/opt/eosio.cdt/bin/wasm-ld: error: duplicate symbol: eosio::send_deferred(unsigned __int128 const&, eosio::name, char const*, unsigned int, bool)
defined in /var/folders/5z/gg3cg17n7rgcfxmxyvwggxjw0000gn/T//addressbook.cpp.o
defined in /var/folders/5z/gg3cg17n7rgcfxmxyvwggxjw0000gn/T//addressbook.cpp.o
```

Need help :(

**Comment by smlu** [comment]
The error you are getting is due to small declaration bug. It should be fixed in branch [release_1.6.x_fixes](https://github.com/EOSIO/eosio.cdt/tree/release_1.6.x_fixes). If for some reason you are not able to compile [release_1.6.x_fixes](https://github.com/EOSIO/eosio.cdt/tree/release_1.6.x_fixes) branch yourself, you can fix this by declaring `send_deferred` an `inline` function in [transaction.hpp:175](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/contracts/eosio/transaction.hpp#L175). See commit: [24d47c9](https://github.com/EOSIO/eosio.cdt/commit/24d47c941be385d47b22798a2b10e46478ed455f#diff-d4d2bd21f7aba986623a94c1f70ad63fR175)

**Comment by form2l1n** [comment]
> The error you are getting is due to small declaration bug. It should be fixed in branch [release_1.6.x_fixes](https://github.com/EOSIO/eosio.cdt/tree/release_1.6.x_fixes). If for some reason you are not able to compile [release_1.6.x_fixes](https://github.com/EOSIO/eosio.cdt/tree/release_1.6.x_fixes) branch yourself, you can fix this by declaring `send_deferred` an `inline` function in [transaction.hpp:175](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/contracts/eosio/transaction.hpp#L175). See commit: [24d47c9](https://github.com/EOSIO/eosio.cdt/commit/24d47c941be385d47b22798a2b10e46478ed455f#diff-d4d2bd21f7aba986623a94c1f70ad63fR175)

That works fine! thx very much~
At the same time, I noticed that the docker and homebrew still have problem version like this, maybe guys can update them too
